[package]
name = "streampaper"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clokwerk = "0.4.0"
diesel = { version = "2.2.0", features = ["r2d2", "sqlite"] }
dotenvy = "0.15.7"
reqwest = { version = "0.12.5", features = ["blocking"] }
rocket = "0.5.1"
