[package]
name = "streampaper"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
clokwerk = "0.3.5"
diesel = { version = "1.4.8", features = ["r2d2", "sqlite"] }
dotenv = "0.15.0"
reqwest = { version = "0.11.6", features = ["blocking"] }
rocket = "0.5.0-rc.1"
