[package]
name = "streampaper"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
clokwerk = "0.4.0"
diesel = { version = "2.2.8", features = ["r2d2", "sqlite"] }
dotenvy = "0.15.7"
reqwest = { version = "0.12.15", features = ["blocking"] }
rocket = "0.5.1"
